#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := edgehog-esp32-device-test

# Include the components directory of the main application:
#
EXTRA_COMPONENT_DIRS := $(realpath ../../examples/edgehog_app/components)

TEST_COMPONENTS ?= edgehog-esp32-device

include $(IDF_PATH)/make/project.mk
