#
# This file is part of Edgehog.
#
# Copyright 2021 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

name: "Edgehog App Build examples"
on:
  # Run when pushing to stable branches
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build-examples:
    strategy:
      matrix:
        idf-version:
          - "4.4"
          - "5.0"
          - "5.1"
          - "5.2"
          - "5.3"
        build-system:
          - idf
    runs-on: ubuntu-latest
    container: espressif/idf:release-v${{ matrix.idf-version }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add to the default configuration the LED enable
        run: |
          echo 'CONFIG_INDICATOR_GPIO_ENABLE=y' >> sdkconfig.defaults
          echo 'CONFIG_INDICATOR_GPIO=1' >> sdkconfig.defaults
        working-directory: ./examples/edgehog_app
        shell: bash
      - name: Build with idf.py
        run: |
          source $IDF_PATH/export.sh
          idf.py reconfigure
          idf.py build
          # Print component size info
          idf.py size-components
        working-directory: ./examples/edgehog_app
        shell: bash
